#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\..\Win32Struct.ahk

/**
 * Describes an exception.
 * @remarks
 * 
  * To enable a debugger to debug a target that is running on a different architecture (32-bit versus 64-bit), use one of the explicit forms of this structure.
  * 
  * 
  * ```cpp
  * typedef struct _EXCEPTION_RECORD32 {
  *     DWORD    ExceptionCode;
  *     DWORD ExceptionFlags;
  *     DWORD ExceptionRecord;
  *     DWORD ExceptionAddress;
  *     DWORD NumberParameters;
  *     DWORD ExceptionInformation[EXCEPTION_MAXIMUM_PARAMETERS];
  * } EXCEPTION_RECORD32, *PEXCEPTION_RECORD32;
  * 
  * typedef struct _EXCEPTION_RECORD64 {
  *     DWORD    ExceptionCode;
  *     DWORD ExceptionFlags;
  *     DWORD64 ExceptionRecord;
  *     DWORD64 ExceptionAddress;
  *     DWORD NumberParameters;
  *     DWORD __unusedAlignment;
  *     DWORD64 ExceptionInformation[EXCEPTION_MAXIMUM_PARAMETERS];
  * } EXCEPTION_RECORD64, *PEXCEPTION_RECORD64;
  * ```
  * 
  * 
 * @see https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-exception_record64
 * @namespace Windows.Win32.System.Diagnostics.Debug
 * @version v4.0.30319
 */
class EXCEPTION_RECORD64 extends Win32Struct
{
    static sizeof => 152

    static packingSize => 8

    /**
     * The reason the exception occurred. This is the code generated by a hardware exception, or the code specified in the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-raiseexception">RaiseException</a> function for a software-generated exception. The following tables describes the exception codes that are likely to occur due to common programming errors. 
     * 
     * 
     * 
     * <table>
     * <tr>
     * <th>Value</th>
     * <th>Meaning</th>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_ACCESS_VIOLATION"></a><a id="exception_access_violation"></a><dl>
     * <dt><b>EXCEPTION_ACCESS_VIOLATION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_ARRAY_BOUNDS_EXCEEDED"></a><a id="exception_array_bounds_exceeded"></a><dl>
     * <dt><b>EXCEPTION_ARRAY_BOUNDS_EXCEEDED</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to access an array element that is out of bounds and the underlying hardware supports bounds checking.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_BREAKPOINT"></a><a id="exception_breakpoint"></a><dl>
     * <dt><b>EXCEPTION_BREAKPOINT</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * A breakpoint was encountered.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_DATATYPE_MISALIGNMENT"></a><a id="exception_datatype_misalignment"></a><dl>
     * <dt><b>EXCEPTION_DATATYPE_MISALIGNMENT</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to read or write data that is misaligned on hardware that does not provide alignment. For example, 16-bit values must be aligned on 2-byte boundaries; 32-bit values on 4-byte boundaries, and so on.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_DENORMAL_OPERAND"></a><a id="exception_flt_denormal_operand"></a><dl>
     * <dt><b>EXCEPTION_FLT_DENORMAL_OPERAND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * One of the operands in a floating-point operation is denormal. A denormal value is one that is too small to represent as a standard floating-point value.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_DIVIDE_BY_ZERO"></a><a id="exception_flt_divide_by_zero"></a><dl>
     * <dt><b>EXCEPTION_FLT_DIVIDE_BY_ZERO</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to divide a floating-point value by a floating-point divisor of zero.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_INEXACT_RESULT"></a><a id="exception_flt_inexact_result"></a><dl>
     * <dt><b>EXCEPTION_FLT_INEXACT_RESULT</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The result of a floating-point operation cannot be represented exactly as a decimal fraction.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_INVALID_OPERATION"></a><a id="exception_flt_invalid_operation"></a><dl>
     * <dt><b>EXCEPTION_FLT_INVALID_OPERATION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * This exception represents any floating-point exception not included in this list.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_OVERFLOW"></a><a id="exception_flt_overflow"></a><dl>
     * <dt><b>EXCEPTION_FLT_OVERFLOW</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The exponent of a floating-point operation is greater than the magnitude allowed by the corresponding type.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_STACK_CHECK"></a><a id="exception_flt_stack_check"></a><dl>
     * <dt><b>EXCEPTION_FLT_STACK_CHECK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The stack overflowed or underflowed as the result of a floating-point operation.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_FLT_UNDERFLOW"></a><a id="exception_flt_underflow"></a><dl>
     * <dt><b>EXCEPTION_FLT_UNDERFLOW</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The exponent of a floating-point operation is less than the magnitude allowed by the corresponding type.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_ILLEGAL_INSTRUCTION"></a><a id="exception_illegal_instruction"></a><dl>
     * <dt><b>EXCEPTION_ILLEGAL_INSTRUCTION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to execute an invalid instruction.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_IN_PAGE_ERROR"></a><a id="exception_in_page_error"></a><dl>
     * <dt><b>EXCEPTION_IN_PAGE_ERROR</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to access a page that was not present, and the system was unable to load the page. For example, this exception might occur if a network connection is lost while running a program over the network.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_INT_DIVIDE_BY_ZERO"></a><a id="exception_int_divide_by_zero"></a><dl>
     * <dt><b>EXCEPTION_INT_DIVIDE_BY_ZERO</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to divide an integer value by an integer divisor of zero.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_INT_OVERFLOW"></a><a id="exception_int_overflow"></a><dl>
     * <dt><b>EXCEPTION_INT_OVERFLOW</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The result of an integer operation caused a carry out of the most significant bit of the result.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_INVALID_DISPOSITION"></a><a id="exception_invalid_disposition"></a><dl>
     * <dt><b>EXCEPTION_INVALID_DISPOSITION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An exception handler returned an invalid disposition to the exception dispatcher. Programmers using a high-level language such as C should never encounter this exception.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_NONCONTINUABLE_EXCEPTION"></a><a id="exception_noncontinuable_exception"></a><dl>
     * <dt><b>EXCEPTION_NONCONTINUABLE_EXCEPTION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to continue execution after a noncontinuable exception occurred.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_PRIV_INSTRUCTION"></a><a id="exception_priv_instruction"></a><dl>
     * <dt><b>EXCEPTION_PRIV_INSTRUCTION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread tried to execute an instruction whose operation is not allowed in the current machine mode.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_SINGLE_STEP"></a><a id="exception_single_step"></a><dl>
     * <dt><b>EXCEPTION_SINGLE_STEP</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * A trace trap or other single-instruction mechanism signaled that one instruction has been executed.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_STACK_OVERFLOW"></a><a id="exception_stack_overflow"></a><dl>
     * <dt><b>EXCEPTION_STACK_OVERFLOW</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The thread used up its stack.
     * 
     * </td>
     * </tr>
     * </table>
     * Â 
     * 
     * Another exception code is likely to occur when debugging console processes. It does not arise because of a programming error. The <b>DBG_CONTROL_C</b> exception code occurs when CTRL+C is input to a console process that handles CTRL+C signals and is being debugged. This exception code is not meant to be handled by applications. It is raised only for the benefit of the debugger, and is raised only when a debugger is attached to the console process.
     * @type {Integer}
     */
    ExceptionCode {
        get => NumGet(this, 0, "int")
        set => NumPut("int", value, this, 0)
    }

    /**
     * The exception flags. This member can be either zero, indicating a continuable exception, or <b>EXCEPTION_NONCONTINUABLE</b> indicating a noncontinuable exception. Any attempt to continue execution after a noncontinuable exception causes the <b>EXCEPTION_NONCONTINUABLE_EXCEPTION</b> exception.
     * @type {Integer}
     */
    ExceptionFlags {
        get => NumGet(this, 4, "uint")
        set => NumPut("uint", value, this, 4)
    }

    /**
     * A pointer to an associated 
     * <b>EXCEPTION_RECORD</b> structure. Exception records can be chained together to provide additional information when nested exceptions occur.
     * @type {Integer}
     */
    ExceptionRecord {
        get => NumGet(this, 8, "uint")
        set => NumPut("uint", value, this, 8)
    }

    /**
     * The address where the exception occurred.
     * @type {Integer}
     */
    ExceptionAddress {
        get => NumGet(this, 16, "uint")
        set => NumPut("uint", value, this, 16)
    }

    /**
     * The number of parameters associated with the exception. This is the number of defined elements in the <b>ExceptionInformation</b> array.
     * @type {Integer}
     */
    NumberParameters {
        get => NumGet(this, 24, "uint")
        set => NumPut("uint", value, this, 24)
    }

    /**
     * 
     * @type {Integer}
     */
    __unusedAlignment {
        get => NumGet(this, 28, "uint")
        set => NumPut("uint", value, this, 28)
    }

    /**
     * An array of additional arguments that describe the exception. The 
     * <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-raiseexception">RaiseException</a> function can specify this array of arguments. For most exception codes, the array elements are undefined. The following table describes the exception codes whose array elements are defined. 
     * 
     * 
     * 
     * <table>
     * <tr>
     * <th>Exception code</th>
     * <th>Meaning</th>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_ACCESS_VIOLATION"></a><a id="exception_access_violation"></a><dl>
     * <dt><b>EXCEPTION_ACCESS_VIOLATION</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The first element of the array contains a read-write flag that indicates the type of operation that caused the access violation. If this value is zero, the thread attempted to read the inaccessible data. If this value is 1, the thread attempted to write to an inaccessible address. 
     * 
     * 
     * If this value is 8, the thread causes a user-mode data execution prevention (DEP) violation.
     * 
     * The second array element specifies the virtual address of the inaccessible data.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="EXCEPTION_IN_PAGE_ERROR"></a><a id="exception_in_page_error"></a><dl>
     * <dt><b>EXCEPTION_IN_PAGE_ERROR</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The first element of the array contains a read-write flag that indicates the type of operation that caused the access violation. If this value is zero, the thread attempted to read the inaccessible data. If this value is 1, the thread attempted to write to an inaccessible address. 
     * 
     * 
     * If this value is 8, the thread causes a user-mode data execution prevention (DEP) violation.
     * 
     * The second array element specifies the virtual address of the inaccessible data.
     * 
     * The third array element specifies the underlying <b>NTSTATUS</b> code that resulted in the exception.
     * 
     * </td>
     * </tr>
     * </table>
     * @type {Array<UInt64>}
     */
    ExceptionInformation{
        get {
            if(!this.HasProp("__ExceptionInformationProxyArray"))
                this.__ExceptionInformationProxyArray := Win32FixedArray(this.ptr + 32, 15, Primitive, "uint")
            return this.__ExceptionInformationProxyArray
        }
    }
}
